# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ff7ea3c65eb60a41a36ad14c0f05e925a6a0a5b928cc4fe5924c15a7451ac83114add6a7b14cca2977c4e5b428757832ba67dc5b95c014ef907e33c846c2847

test:
  secret_key_base: ed11b396b5262ca32f7808d1fd4992d1112a86e7a27aa5fbc320dbd92ff8acb63e1b5ad77549754cd7973c4a575f9782f9ede9a163b541f76e13019756e76c1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
